# Generated by Django 6.1.1 on 2026-09-27 14:09

import bank.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('alert', 'Alert'), ('message', 'Message')], max_length=10)),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Urgent')], default='info', max_length=10)),
                ('sender_name', models.CharField(blank=True, default='Kwetu Bank', max_length=100)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'kind', 'read_at', '-created_at'], name='notif_user_kind_read_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, default=bank.models.generate_transaction_id, editable=False, max_length=10, unique=True, verbose_name='Transaction ID')),
                ('type', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdrawal'), ('T', 'Transfer')], max_length=1, verbose_name='Type of Transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['account', '-date'], name='txn_account_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('is_fraud', models.BooleanField(default=False, verbose_name='Fraud')),
                ('fraud_probability', models.FloatField(blank=True, null=True)),
                ('fraud_model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('fraud_threshold', models.FloatField(blank=True, null=True)),
                ('receiver_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transaction_logs', to=settings.AUTH_USER_MODEL)),
                ('sender_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transaction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['sender_account', '-date'], name='txlog_sender_date_idx'), models.Index(fields=['receiver_account', '-date'], name='txlog_receiver_date_idx'), models.Index(fields=['is_fraud', '-date'], name='txlog_fraud_date_idx')],
            },
        ),
    ]
