# Generated by Django 4.1.1 on 2022-11-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_alter_transaction_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date"),
        ),
    ]
