# Generated by Django 4.1.1 on 2022-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0004_transactionlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionlogs",
            name="rec_cc_number",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="Receiver Credit Card Number",
            ),
        ),
    ]
