# Generated by Django 4.1.1 on 2022-11-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0005_transactionlogs_rec_cc_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionlogs",
            options={
                "verbose_name": "Transaction Logs",
                "verbose_name_plural": "Transaction Logs",
            },
        ),
        migrations.AlterField(
            model_name="transactionlogs",
            name="cc_number",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="creditcard_number"
            ),
        ),
        migrations.AlterField(
            model_name="transactionlogs",
            name="rec_cc_number",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="receiver_creditcard"
            ),
        ),
        migrations.AlterField(
            model_name="transactionlogs",
            name="receiver",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="receiver"
            ),
        ),
        migrations.AlterField(
            model_name="transactionlogs",
            name="sender",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="sender"
            ),
        ),
    ]
