# Generated by Django 4.1.1 on 2022-09-26 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="national_id",
            field=models.IntegerField(
                default=0,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(7)],
                verbose_name="National ID",
            ),
        ),
    ]
