# Generated by Django 4.1.1 on 2022-10-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual", "Individual"),
                    ("business", "Business"),
                    ("joint", "Joint"),
                    ("power of attorney", "Power of Attorney"),
                ],
                default="individual",
                max_length=50,
                null=True,
                verbose_name="User Type",
            ),
        ),
    ]
