# Generated by Django 4.1.1 on 2022-11-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Blocked"),
        ),
    ]
