# Generated by Django 4.1.1 on 2022-10-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("checking", "Checking"),
                    ("savings", "Savings"),
                    ("certificate of deposit", "Certificate of Deposit"),
                    ("money market", "Money Market"),
                ],
                default="savings",
                max_length=50,
                verbose_name="Type of Account",
            ),
        ),
    ]
